version: "3.8"

services:
  mysql:
    container_name: mysql-flask-app
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "ashwin"
    ports:
      - "3306:3306"
    volumes:
      - mysql-flask-app:/var/lib/mysql
    networks:
      - flask-backend-ntwk
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s

  flask:
    image: ashwin369/flask-backend-app:latest
    container_name: flask-backend-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: ashwin
    networks:
      - flask-backend-ntwk
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql-flask-app:

networks:
  flask-backend-ntwk:
